version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    reviewers:
      - 'kaff4/kaff4-maintainers'
    schedule:
      interval: "daily"
      time: '09:00'
      timezone: 'America/Toronto'
    ignore:
      # Misk updates daily, there's little to no benefit to these
      # updates, so we only do it monthly.
      - dependency-name: "misk"
        update-types: ["version-update:semver-patch"]
