formatting:
  active: true
  Indentation:
    active: true
    indentSize: 2

style:
  active: true
  ForbiddenImport:
    active: true
    imports: [ 'com.google.inject.Inject', 'com.google.inject.Provider', 'com.google.inject.Singleton' ]
    forbiddenPatterns: ''

complexity:
  LongMethod:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]

