name: Check JVM
on: [ push ]
jobs:
  JVM-Run-Gradle-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build kaff4
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: check buildHealth --continue

      - name: Verify build health
        run: ./hooks/check-dependencies.sh

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-reports
          path: ./**/build/reports/
