name: Check JVM
on: [push]
jobs:
  JVM-Run-Gradle-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ./engine-jvm
                  
          # Only write to the cache for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Execute gradlew check
        working-directory: ./engine-jvm
        run: ./gradlew check --continue 

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-reports
          path: engine-jvm/**/build/reports/
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
