name: Check JVM
on: [push]
jobs:
  JVM-Run-Gradle-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build kaff4
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: check --continue 

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-reports
          path: ./**/build/reports/
